### ISSUE TITLE
Readme and installation Instructions missing

### ISSUE THREAD

**Issue by dzeitman** [Mach1Studios/m1-webdemos#4]
Be awesome if there was a readme that contained steps to install and run these demos.

**Comment by himwho** [comment]
honestly our intention was to let people build from this repo: https://github.com/Mach1Studios/m1-web-spatialaudioplayer which has more instructions

but you do make a good point, why not also include build instructions here for local play

**Comment by himwho** [comment]
added a readme and content file steps as suggested! 

just a fair warning, all the content demos combined are a hefty download!
